//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace LuminousMpartnerIB.com.luminousindia.lumapi {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback sendsmsOperationCompleted;
        
        private System.Threading.SendOrPostCallback sendsmsIMIOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::LuminousMpartnerIB.Properties.Settings.Default.LuminousMpartnerIB_com_luminousindia_lumapi_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event sendsmsCompletedEventHandler sendsmsCompleted;
        
        /// <remarks/>
        public event sendsmsIMICompletedEventHandler sendsmsIMICompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/sendsms", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string sendsms(string mob, string mess, string employee, string token) {
            object[] results = this.Invoke("sendsms", new object[] {
                        mob,
                        mess,
                        employee,
                        token});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void sendsmsAsync(string mob, string mess, string employee, string token) {
            this.sendsmsAsync(mob, mess, employee, token, null);
        }
        
        /// <remarks/>
        public void sendsmsAsync(string mob, string mess, string employee, string token, object userState) {
            if ((this.sendsmsOperationCompleted == null)) {
                this.sendsmsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendsmsOperationCompleted);
            }
            this.InvokeAsync("sendsms", new object[] {
                        mob,
                        mess,
                        employee,
                        token}, this.sendsmsOperationCompleted, userState);
        }
        
        private void OnsendsmsOperationCompleted(object arg) {
            if ((this.sendsmsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sendsmsCompleted(this, new sendsmsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/sendsmsIMI", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string sendsmsIMI(string mob, string mess, string token, string msgtype, string reftext) {
            object[] results = this.Invoke("sendsmsIMI", new object[] {
                        mob,
                        mess,
                        token,
                        msgtype,
                        reftext});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void sendsmsIMIAsync(string mob, string mess, string token, string msgtype, string reftext) {
            this.sendsmsIMIAsync(mob, mess, token, msgtype, reftext, null);
        }
        
        /// <remarks/>
        public void sendsmsIMIAsync(string mob, string mess, string token, string msgtype, string reftext, object userState) {
            if ((this.sendsmsIMIOperationCompleted == null)) {
                this.sendsmsIMIOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendsmsIMIOperationCompleted);
            }
            this.InvokeAsync("sendsmsIMI", new object[] {
                        mob,
                        mess,
                        token,
                        msgtype,
                        reftext}, this.sendsmsIMIOperationCompleted, userState);
        }
        
        private void OnsendsmsIMIOperationCompleted(object arg) {
            if ((this.sendsmsIMICompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sendsmsIMICompleted(this, new sendsmsIMICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void sendsmsCompletedEventHandler(object sender, sendsmsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sendsmsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sendsmsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void sendsmsIMICompletedEventHandler(object sender, sendsmsIMICompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sendsmsIMICompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sendsmsIMICompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591