//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuminousMpartnerIB.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllPage
    {
        public int Id { get; set; }
        public string PageName { get; set; }
        public string ModuleName { get; set; }
        public string RequestType { get; set; }
        public int RootNode { get; set; }
        public Nullable<bool> IsTopMenu { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public string Image { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyOn { get; set; }
    }
}
