//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luminous.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Callingsample
    {
        public int id { get; set; }
        public string Product_Serial_Number { get; set; }
        public string Dlr_Name { get; set; }
        public string Dlr_Phone { get; set; }
        public string Dis_Name { get; set; }
        public string Dis_Address_ContactNo { get; set; }
        public string Customer_Name { get; set; }
        public string Customer_Phone { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> Product_Purchase_Date { get; set; }
        public Nullable<int> Flag { get; set; }
        public Nullable<System.DateTime> Mod_date { get; set; }
    }
}
