//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuminousMpartnerIB.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card_CardData
    {
        public decimal Id { get; set; }
        public Nullable<decimal> DynamicHomePageId { get; set; }
        public Nullable<decimal> CardProviderId { get; set; }
        public string Title { get; set; }
        public string Background_image { get; set; }
        public string Main_image { get; set; }
        public string DeepLink { get; set; }
        public string Image_height { get; set; }
        public string Image_width { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> Status { get; set; }
        public string ProductFooterId { get; set; }
        public string ProductFooter { get; set; }
        public string ProductUpperId { get; set; }
        public string ProductUpper { get; set; }
        public string ProductMainId { get; set; }
        public string ProductMain { get; set; }
    }
}
