//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuminousMpartnerIB.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card_dynamicPage
    {
        public decimal Id { get; set; }
        public string CardProviderId { get; set; }
        public string CardProviderName { get; set; }
        public string CardActionId { get; set; }
        public string ClassName { get; set; }
        public string CardAction_Deeplink { get; set; }
        public string CardAction_Pagename { get; set; }
        public string ColourId { get; set; }
        public string ColourName { get; set; }
        public string Hexacode { get; set; }
        public string ImageOriginalName { get; set; }
        public string ImageSystemName { get; set; }
        public string Height { get; set; }
        public string Width { get; set; }
        public string Title { get; set; }
        public string Sub_Title { get; set; }
        public string Sub_TitleColour { get; set; }
        public string CardDataFlag { get; set; }
        public string Action1_Colour { get; set; }
        public string Action1_Text { get; set; }
        public Nullable<System.DateTime> Startdate { get; set; }
        public Nullable<System.DateTime> Enddate { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> Status { get; set; }
        public string TitleColour { get; set; }
        public string Pagename { get; set; }
        public string PdfOriginalName { get; set; }
        public string PdfSystemName { get; set; }
        public string Subcatid { get; set; }
        public string Subcatname { get; set; }
        public string OriginalMainImage { get; set; }
        public string SystemMainImage { get; set; }
        public Nullable<int> Sequence { get; set; }
    }
}
