//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luminous.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DestributorList
    {
        public DestributorList()
        {
            this.DestributorsHistories = new HashSet<DestributorsHistory>();
            this.Dealers = new HashSet<Dealer>();
            this.DealersHistories = new HashSet<DealersHistory>();
            this.ProductAccessTables = new HashSet<ProductAccessTable>();
            this.ProductAccessTables1 = new HashSet<ProductAccessTable>();
            this.ProductAccessTables2 = new HashSet<ProductAccessTable>();
            this.ProductAccessTableForProducts = new HashSet<ProductAccessTableForProduct>();
            this.NotificationAccessTables = new HashSet<NotificationAccessTable>();
            this.NotificationAccessTables1 = new HashSet<NotificationAccessTable>();
            this.NotificationAccessTables2 = new HashSet<NotificationAccessTable>();
            this.AlertNotificationAccessTables = new HashSet<AlertNotificationAccessTable>();
            this.AlertNotificationAccessTables1 = new HashSet<AlertNotificationAccessTable>();
            this.AlertNotificationAccessTables2 = new HashSet<AlertNotificationAccessTable>();
            this.UsersLists = new HashSet<UsersList>();
            this.Price_SchemeAccessTable = new HashSet<Price_SchemeAccessTable>();
        }
    
        public int id { get; set; }
        public Nullable<int> RegionId { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> Createtime { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Updatetime { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual Region Region { get; set; }
        public virtual ICollection<DestributorsHistory> DestributorsHistories { get; set; }
        public virtual ICollection<Dealer> Dealers { get; set; }
        public virtual ICollection<DealersHistory> DealersHistories { get; set; }
        public virtual ICollection<ProductAccessTable> ProductAccessTables { get; set; }
        public virtual ICollection<ProductAccessTable> ProductAccessTables1 { get; set; }
        public virtual ICollection<ProductAccessTable> ProductAccessTables2 { get; set; }
        public virtual ICollection<ProductAccessTableForProduct> ProductAccessTableForProducts { get; set; }
        public virtual ICollection<NotificationAccessTable> NotificationAccessTables { get; set; }
        public virtual ICollection<NotificationAccessTable> NotificationAccessTables1 { get; set; }
        public virtual ICollection<NotificationAccessTable> NotificationAccessTables2 { get; set; }
        public virtual ICollection<AlertNotificationAccessTable> AlertNotificationAccessTables { get; set; }
        public virtual ICollection<AlertNotificationAccessTable> AlertNotificationAccessTables1 { get; set; }
        public virtual ICollection<AlertNotificationAccessTable> AlertNotificationAccessTables2 { get; set; }
        public virtual ICollection<UsersList> UsersLists { get; set; }
        public virtual ICollection<Price_SchemeAccessTable> Price_SchemeAccessTable { get; set; }
    }
}
