//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luminous.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsertContextHistory
    {
        public int Id { get; set; }
        public Nullable<int> InserContextId { get; set; }
        public string ImageEncode { get; set; }
        public string DealerName { get; set; }
        public string DealerCity { get; set; }
        public string DealerPhone { get; set; }
        public string DealerEmail { get; set; }
        public string DistributorCode { get; set; }
        public string Empcode { get; set; }
        public string DealerID { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyOn { get; set; }
        public string Rating { get; set; }
        public string RatingBy { get; set; }
        public Nullable<System.DateTime> RatingOn { get; set; }
    }
}
