//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luminous.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lsd_GiftMaster_History
    {
        public long GiftId_his { get; set; }
        public Nullable<int> GiftId { get; set; }
        public string GiftName { get; set; }
        public string GiftDesc { get; set; }
        public string GiftImage { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
