//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luminous.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class luminious_Update
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Textbody { get; set; }
        public string ImageFileName { get; set; }
        public string ImageName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> Expirydate { get; set; }
        public Nullable<int> Status { get; set; }
        public string Createdby { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyOn { get; set; }
        public string VideoURL { get; set; }
        public Nullable<int> ParentCatid { get; set; }
        public Nullable<int> ProductLevelOne { get; set; }
        public Nullable<int> ProductLeveltwo { get; set; }
        public Nullable<int> ProductLevelThreeId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> Media { get; set; }
        public Nullable<int> RedirectPage { get; set; }
    }
}
