//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuminousMpartnerIB.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MHrOtp
    {
        public decimal seqid { get; set; }
        public string empid { get; set; }
        public string imeinumber { get; set; }
        public string osversion { get; set; }
        public string devicename { get; set; }
        public string otp { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public string otpstatus { get; set; }
        public Nullable<System.DateTime> varifiedon { get; set; }
        public Nullable<System.DateTime> expireon { get; set; }
        public string appversion { get; set; }
        public string appid { get; set; }
        public string devid { get; set; }
        public string ostype { get; set; }
    }
}
