//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luminous.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermotionTypeHistory
    {
        public int id { get; set; }
        public Nullable<int> PerTypeId { get; set; }
        public string PType { get; set; }
        public Nullable<int> PlTwStatus { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual PermotionType PermotionType { get; set; }
    }
}
