//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luminous.EF
{
    using LuminousMpartnerIB.EF;
    using System;
    using System.Collections.Generic;
    
    public partial class ProductLevelThreefHistory
    {
        public int id { get; set; }
        public Nullable<int> ProductLevelThreeId { get; set; }
        public Nullable<int> PrductID { get; set; }
        public Nullable<int> pc_Lvl_Id { get; set; }
        public Nullable<int> pc_Lv2_Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> PlTwStatus { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual ProductLevelOne ProductLevelOne { get; set; }
        public virtual ProductLevelThreef ProductLevelThreef { get; set; }
        public virtual ProductLevelTwo ProductLevelTwo { get; set; }
        public virtual ProductCatergory ProductCatergory { get; set; }
    }
}
