//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luminous.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPermotion
    {
        public int id { get; set; }
        public Nullable<int> PTypeId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> ProductLvlOne { get; set; }
        public string Discription { get; set; }
        public string PerImage { get; set; }
        public Nullable<int> PrStatus { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
    
        public virtual PermotionType PermotionType { get; set; }
        public virtual ProductLevelOne ProductLevelOne { get; set; }
        public virtual ProductCatergory ProductCatergory { get; set; }
    }
}
