//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luminous.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductImagesHistory
    {
        public int id { get; set; }
        public Nullable<int> ProductImageId { get; set; }
        public Nullable<int> pc_Lv3_oneId { get; set; }
        public string PrImage { get; set; }
        public string Name { get; set; }
        public Nullable<int> PlTwStatus { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
    
        public virtual ProductImage ProductImage { get; set; }
    }
}
