//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuminousMpartnerIB.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductLevelThreeHistory
    {
        public int id { get; set; }
        public Nullable<int> Pr_Lvl_3_ID { get; set; }
        public Nullable<int> pc_Lv2_oneId { get; set; }
        public string PrCode { get; set; }
        public string PrDiscription { get; set; }
        public string Name { get; set; }
        public Nullable<int> PlTwStatus { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public Nullable<int> productCategoryid { get; set; }
        public Nullable<int> ProductLevelOne { get; set; }
        public Nullable<decimal> MRP { get; set; }
        public string Warrenty { get; set; }
        public string KeyFeature { get; set; }
        public string brochure { get; set; }
        public string Rating { get; set; }
        public string MaximumChargeCurrent { get; set; }
        public string NoOfBattery { get; set; }
        public string SupportedBatteryType { get; set; }
        public string Maximumbulbload { get; set; }
        public string Technology { get; set; }
        public string NominalVoltage { get; set; }
        public string DimensionMM { get; set; }
        public string Weight_Filled_battery { get; set; }
    }
}
