//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuminousMpartnerIB.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Region
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> Createtime { get; set; }
        public string createBy { get; set; }
        public Nullable<System.DateTime> Updatetime { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> status { get; set; }
        public string RegionCode { get; set; }
    }
}
