//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuminousMpartnerIB.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaveNotificationSurvey
    {
        public int ID { get; set; }
        public string UserId { get; set; }
        public string DeviceId { get; set; }
        public Nullable<int> SurveyID { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyOn { get; set; }
        public string Options { get; set; }
        public string OptionValue { get; set; }
        public Nullable<int> ContestId { get; set; }
        public Nullable<int> Marqueeid { get; set; }
    }
}
