//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuminousMpartnerIB.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suggestion
    {
        public int id { get; set; }
        public Nullable<int> FunctionID { get; set; }
        public string Suggestion1 { get; set; }
        public string ImageName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string createdBy { get; set; }
        public Nullable<bool> SentMailStatus { get; set; }
        public Nullable<System.DateTime> SentMailDate { get; set; }
        public string CustName { get; set; }
        public string Email { get; set; }
    }
}
