//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuminousMpartnerIB.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersListHistory
    {
        public int id { get; set; }
        public Nullable<int> UserlistId { get; set; }
        public string UserId { get; set; }
        public string UPassword { get; set; }
        public Nullable<int> RegId { get; set; }
        public Nullable<int> DestriId { get; set; }
        public Nullable<int> DealerId { get; set; }
        public string CustomerType { get; set; }
        public string Dis_Sap_Code { get; set; }
        public string Dis_Name { get; set; }
        public string Dis_Address1 { get; set; }
        public string Dis_Address2 { get; set; }
        public string Dis_City { get; set; }
        public string Dis_District { get; set; }
        public string Dis_State { get; set; }
        public string Dis_ContactNo { get; set; }
        public string Dis_Email { get; set; }
        public string Region_code { get; set; }
        public Nullable<int> isActive { get; set; }
        public string ActivatedBY { get; set; }
        public Nullable<System.DateTime> ActivatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedbY { get; set; }
        public string BlockedBy { get; set; }
        public Nullable<System.DateTime> BlockedDATE { get; set; }
        public string ProfileImage { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public string GoogleAddress { get; set; }
    }
}
