//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuminousMpartnerIB.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class useraccount
    {
        public int id { get; set; }
        public string userid { get; set; }
        public string password { get; set; }
        public string status { get; set; }
        public string approvallevel { get; set; }
        public string assignedto { get; set; }
        public Nullable<int> profileid { get; set; }
        public string email { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public string updatedby { get; set; }
        public Nullable<System.DateTime> updatedtime { get; set; }
        public Nullable<System.DateTime> deletedtime { get; set; }
        public string deletedby { get; set; }
        public string approvalcreatedby { get; set; }
        public Nullable<System.DateTime> approvalcreattime { get; set; }
        public Nullable<int> autoid { get; set; }
    }
}
