//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luminous.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRS_Datecheck
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> NewDate { get; set; }
        public Nullable<System.DateTime> OldDate { get; set; }
        public Nullable<System.DateTime> Maxdate { get; set; }
        public Nullable<System.DateTime> Mindate { get; set; }
    }
}
