//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuminousMpartnerIB.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlertNotificationReadStatu
    {
        public int id { get; set; }
        public Nullable<int> NotificationId { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public string UserId { get; set; }
        public string DeviceId { get; set; }
    }
}
