//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luminous.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllGroup
    {
        public int regionID { get; set; }
        public string regionName { get; set; }
        public Nullable<int> DestributorId { get; set; }
        public string DestributorName { get; set; }
        public Nullable<int> DealersID { get; set; }
        public string DealerName { get; set; }
    }
}
