//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luminous.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class allstate_history
    {
        public int id { get; set; }
        public string statename { get; set; }
        public string createdtime { get; set; }
        public string updatedtime { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> deletedtime { get; set; }
        public string updatedby { get; set; }
        public string deletedby { get; set; }
    }
}
