//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuminousMpartnerIB.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class App_Log
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string Url { get; set; }
        public string Api_Name { get; set; }
        public string Page_Name { get; set; }
        public string Exception_Name { get; set; }
        public Nullable<int> Line_No { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string DeviceId { get; set; }
        public string AppVersion { get; set; }
        public string OSVersion { get; set; }
        public string OSType { get; set; }
        public string OS_Version_Code { get; set; }
        public string IP_Address { get; set; }
        public string Screen_Name { get; set; }
        public string Network_Type { get; set; }
        public string Network_Operator { get; set; }
        public string Time_Captured { get; set; }
        public string Channel { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
