//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luminous.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BannerHistory
    {
        public int id { get; set; }
        public Nullable<int> BannerId { get; set; }
        public string Header_Details { get; set; }
        public string Sub_Header_Details { get; set; }
        public string Banner_Details { get; set; }
        public string BannerFileName { get; set; }
        public Nullable<int> BannerSize { get; set; }
        public string BannerImage { get; set; }
        public Nullable<System.DateTime> stardate { get; set; }
        public Nullable<System.DateTime> ExpriyDate { get; set; }
        public Nullable<int> BStatus { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<int> ParentCatid { get; set; }
        public Nullable<int> ProductLevelOne { get; set; }
        public Nullable<int> ProductLeveltwo { get; set; }
        public Nullable<int> ProductLevelThreeId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> Months { get; set; }
        public Nullable<int> Media { get; set; }
        public Nullable<int> RedirectPage { get; set; }
    
        public virtual Banner Banner { get; set; }
    }
}
