//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luminous.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConnectAssist_log
    {
        public long Id { get; set; }
        public Nullable<long> ParentId { get; set; }
        public string Userid { get; set; }
        public string Srno { get; set; }
        public string CreatedBy { get; set; }
        public string Flag { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ResolvedDate { get; set; }
        public Nullable<System.DateTime> InProcessDate { get; set; }
        public string DistCode { get; set; }
        public string DistName { get; set; }
        public string CustName { get; set; }
        public string CustMobile { get; set; }
        public string Adderss { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public Nullable<System.DateTime> DateOfSale { get; set; }
        public string Message { get; set; }
        public string ConnectplusImage { get; set; }
        public string DlrCode { get; set; }
        public string CustLandLine { get; set; }
    }
}
