//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuminousMpartnerIB.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EscalationMatrix_History
    {
        public long Id { get; set; }
        public Nullable<long> Pid { get; set; }
        public Nullable<int> StateId { get; set; }
        public string ServiceCenterName { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> status { get; set; }
        public string Phoneno { get; set; }
    }
}
