//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luminous.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class functionalgroup
    {
        public int id { get; set; }
        public string fname { get; set; }
        public string Femail { get; set; }
        public string FdepartmentName { get; set; }
        public string FDeparmentPersonName { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> createdTime { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> ModofiedDate { get; set; }
        public string ModifiedBy { get; set; }
    }
}
