//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuminousMpartnerIB.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class GCM_NotificationLog
    {
        public decimal Id { get; set; }
        public string SapCode { get; set; }
        public string Regid { get; set; }
        public string ApiKey { get; set; }
        public string PostData { get; set; }
        public string PostContent_Type { get; set; }
        public string ResponseStatus { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
    }
}
