//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luminous.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsertContext
    {
        public int Id { get; set; }
        public string ImageEncode { get; set; }
        public string DealerName { get; set; }
        public string DealerCity { get; set; }
        public string DealerPhone { get; set; }
        public string DealerEmail { get; set; }
        public string DistributorCode { get; set; }
        public string EmpCode { get; set; }
        public string DealerId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyOn { get; set; }
        public string Rating { get; set; }
        public string RatingBy { get; set; }
        public Nullable<System.DateTime> RatingOn { get; set; }
        public Nullable<int> Status { get; set; }
        public string DealerState { get; set; }
        public string FseName { get; set; }
        public string ParentCategory { get; set; }
        public string DealerFirmName { get; set; }
        public string ASMEmpCode { get; set; }
        public string FSE_DealerMobileNo { get; set; }
    }
}
