//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luminous.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class LSD_DealerCouponCount
    {
        public long Id { get; set; }
        public Nullable<int> Glod_DealerEligibleCoupon { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> Gold_DealerRedeemedCoupon { get; set; }
        public Nullable<int> Gold_DealerBalanceCount { get; set; }
        public Nullable<int> Gold_DealerRedeemedCount { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Dealer_ReedemedCount { get; set; }
    }
}
