//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luminous.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class LSD_TNCMaster
    {
        public int Id { get; set; }
        public string Tnc { get; set; }
        public string Schemeinfo { get; set; }
        public string UserType { get; set; }
        public string Module { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifyOn { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<int> Status { get; set; }
        public string Img { get; set; }
    }
}
