//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luminous.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class LSD_Master
    {
        public long Id { get; set; }
        public string QrCode { get; set; }
        public string Barcode { get; set; }
        public string SecretCode { get; set; }
        public string BundleCode { get; set; }
        public Nullable<int> GiftId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public string ActivationDistCode { get; set; }
        public string ActivationDistName { get; set; }
        public string ActivatedQrCode { get; set; }
        public Nullable<System.DateTime> ActivationDistOn { get; set; }
        public string RedemptionDealerCode { get; set; }
        public string RedemptionDealerName { get; set; }
        public string RedemtionDealerBarCode { get; set; }
        public string RedemptionDealerSecretCode { get; set; }
        public Nullable<System.DateTime> RedemptionDealerOn { get; set; }
        public string ClaimDistCode { get; set; }
        public Nullable<System.DateTime> ClaimDistOn { get; set; }
        public Nullable<int> Status { get; set; }
        public string CouponType { get; set; }
    }
}
