//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luminous.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MapConnectAssist_Comments
    {
        public int id { get; set; }
        public Nullable<int> ConnectAssistId { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string Attachment { get; set; }
        public string filename { get; set; }
    
        public virtual ConnectAssist ConnectAssist { get; set; }
    }
}
