//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuminousMpartnerIB.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mapping_Productlevelthree_TechnicalSpecification
    {
        public long Id { get; set; }
        public Nullable<int> Productid { get; set; }
        public Nullable<int> ProductCatId { get; set; }
        public Nullable<int> ColumnId { get; set; }
        public string Value { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
