//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuminousMpartnerIB.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MediaDataHistory
    {
        public int Id { get; set; }
        public Nullable<int> MediaDataId { get; set; }
        public string VideoName { get; set; }
        public string Url { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyOn { get; set; }
        public string VideoImage { get; set; }
        public Nullable<int> LabelId { get; set; }
        public Nullable<int> Status { get; set; }
        public string PageFlag { get; set; }
    }
}
