//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luminous.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class pageallow
    {
        public int id { get; set; }
        public Nullable<int> profileid { get; set; }
        public Nullable<int> pageid { get; set; }
        public Nullable<int> createrole { get; set; }
        public Nullable<int> editrole { get; set; }
        public Nullable<int> deleterole { get; set; }
        public Nullable<int> uview { get; set; }
    }
}
