//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luminous.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermotionsList
    {
        public PermotionsList()
        {
            this.PermotionsListHistories = new HashSet<PermotionsListHistory>();
            this.ProductAccessTables = new HashSet<ProductAccessTable>();
        }
    
        public int id { get; set; }
        public Nullable<int> PermotionTypeId { get; set; }
        public Nullable<int> ProductCatId { get; set; }
        public Nullable<int> ProductLvlOneId { get; set; }
        public string Descriptions { get; set; }
        public string ImageName { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> Enddate { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public string createby { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
        public string Modifiedby { get; set; }
        public string PDFName { get; set; }
        public Nullable<int> ParentCatid { get; set; }
    
        public virtual ParentCategory ParentCategory { get; set; }
        public virtual PermotionType PermotionType { get; set; }
        public virtual ProductLevelOne ProductLevelOne { get; set; }
        public virtual ICollection<PermotionsListHistory> PermotionsListHistories { get; set; }
        public virtual ICollection<ProductAccessTable> ProductAccessTables { get; set; }
        public virtual ProductCatergory ProductCatergory { get; set; }
    }
}
