//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luminous.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermotionType
    {
        public PermotionType()
        {
            this.ProductPermotions = new HashSet<ProductPermotion>();
            this.PermotionTypeHistories = new HashSet<PermotionTypeHistory>();
            this.PermotionsLists = new HashSet<PermotionsList>();
        }
    
        public int id { get; set; }
        public string PType { get; set; }
        public Nullable<int> PlTwStatus { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual ICollection<ProductPermotion> ProductPermotions { get; set; }
        public virtual ICollection<PermotionTypeHistory> PermotionTypeHistories { get; set; }
        public virtual ICollection<PermotionsList> PermotionsLists { get; set; }
    }
}
