//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuminousMpartnerIB.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductLevelThree
    {
        public int id { get; set; }
        public Nullable<int> pc_Lv2_oneId { get; set; }
        public string PrCode { get; set; }
        public string PrDiscription { get; set; }
        public string Name { get; set; }
        public Nullable<int> PlTwStatus { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public Nullable<int> productCategoryid { get; set; }
        public Nullable<int> ProductLevelOne { get; set; }
        public Nullable<int> productLevelThreefId { get; set; }
        public Nullable<decimal> MRP { get; set; }
        public string Warrenty { get; set; }
        public string KeyFeature { get; set; }
        public string brochure { get; set; }
        public string Rating { get; set; }
        public Nullable<int> ParentCatid { get; set; }
        public Nullable<int> OrderSequence { get; set; }
        public string MaximumChargeCurrent { get; set; }
        public string NoOfBattery { get; set; }
        public string SupportedBatteryType { get; set; }
        public string Maximumbulbload { get; set; }
        public string Technology { get; set; }
        public string NominalVoltage { get; set; }
        public string DimensionMM { get; set; }
        public string Weight_Filled_battery { get; set; }
        public string RatedCapacity { get; set; }
        public string FilledWeight { get; set; }
        public string DCOutputVoltage { get; set; }
        public string DCOutputCurrent { get; set; }
        public string MaxSupportedPanelpower { get; set; }
        public string MaxSolarPanelVoltage { get; set; }
        public string VA { get; set; }
        public string NoofCells { get; set; }
        public string PeakPowerPMax { get; set; }
        public string RatedModuleVoltage { get; set; }
        public string MaximumPowerVoltage { get; set; }
        public string MaximumPowerCurrent { get; set; }
        public string NominalDCOutputVoltage { get; set; }
        public string MaxDCOutputCurrent { get; set; }
        public string Noof12VBatteriesinSeries { get; set; }
        public string SolarLength { get; set; }
        public string SolarWidth { get; set; }
        public string Heightuptofloattop { get; set; }
        public string DryWeight { get; set; }
        public string RatedACpower { get; set; }
        public string OperatingVoltage { get; set; }
        public string ChargeControllerRating { get; set; }
        public string NominalBatterybankvoltage { get; set; }
        public string InputVoltageWorkingRange { get; set; }
        public string OutputVoltageWorkingRange { get; set; }
        public string MainsACLowCut { get; set; }
        public string MainACLowCutRecovery { get; set; }
    
        public virtual ProductCatergory ProductCatergory { get; set; }
        public virtual ProductLevelTwo ProductLevelTwo { get; set; }
    }
}
