//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuminousMpartnerIB.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCatergory
    {
        public int id { get; set; }
        public string PCode { get; set; }
        public string PName { get; set; }
        public int Pstatus { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> ParentCatid { get; set; }
        public Nullable<int> ordersequence { get; set; }
        public string PdfOriginalName { get; set; }
        public string PdfSystemName { get; set; }
    
        public virtual ParentCategory ParentCategory { get; set; }
    }
}
