//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuminousMpartnerIB.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductLevelOne
    {
        public int id { get; set; }
        public Nullable<int> pcId { get; set; }
        public string Name { get; set; }
        public Nullable<int> PlStatus { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public Nullable<int> ParentCatid { get; set; }
        public Nullable<int> OrderSequence { get; set; }
    
        public virtual ProductCatergory ProductCatergory { get; set; }
    }
}
