//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luminous.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegionsHistroy
    {
        public int id { get; set; }
        public Nullable<int> RegionId { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> Updatetime { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> status { get; set; }
        public string RegionCode { get; set; }
    
        public virtual Region Region { get; set; }
    }
}
