//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luminous.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaveDelContestImage
    {
        public int Id { get; set; }
        public string DealerCode { get; set; }
        public string DistributorCode { get; set; }
        public string ImageName { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> Contestid { get; set; }
        public Nullable<int> Marqueeid { get; set; }
        public string Rating { get; set; }
        public string RatingBy { get; set; }
        public Nullable<System.DateTime> RatingOn { get; set; }
        public string PollFlag { get; set; }
        public string PollSubmitFlag { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Location { get; set; }
    }
}
