//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luminous.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchemeSlab
    {
        public SchemeSlab()
        {
            this.SchemeSlabHistories = new HashSet<SchemeSlabHistory>();
        }
    
        public int SlabId { get; set; }
        public Nullable<int> StartRange { get; set; }
        public Nullable<int> EndRange { get; set; }
        public string Gift { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyOn { get; set; }
        public string SchemeId { get; set; }
    
        public virtual ICollection<SchemeSlabHistory> SchemeSlabHistories { get; set; }
    }
}
