//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luminous.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShowMarquee_Text_History
    {
        public int Id { get; set; }
        public Nullable<int> MarqueeID { get; set; }
        public string Marqueetext { get; set; }
        public Nullable<int> MarqueeFlag { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> Statrtdate { get; set; }
        public Nullable<System.DateTime> Enddate { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ContestId { get; set; }
    }
}
