//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuminousMpartnerIB.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserVerification_log
    {
        public int LoggedID { get; set; }
        public int Id { get; set; }
        public string UserId { get; set; }
        public string Otp { get; set; }
        public string DeviceId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string OSType { get; set; }
        public string OSVersion { get; set; }
        public string AppVersion { get; set; }
        public string UnBolckedBy { get; set; }
        public string UnauthorizedUser { get; set; }
        public Nullable<int> Status { get; set; }
        public string Token { get; set; }
        public Nullable<int> TokenFlag { get; set; }
        public Nullable<System.DateTime> modifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public string Fcm_token { get; set; }
        public string languageCode { get; set; }
        public Nullable<System.DateTime> LoggedDate { get; set; }
    }
}
