//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luminous.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class WC_Connect_Update_customer_detail_log
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Proc_CallDate { get; set; }
        public Nullable<int> Status { get; set; }
        public string ErrorDescription { get; set; }
        public string LogBy { get; set; }
    }
}
