//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luminous.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wc_Warranty_Collection_Data_History
    {
        public int Id { get; set; }
        public string Product_Serial_Number { get; set; }
        public string Product_Type { get; set; }
        public string Product_Model { get; set; }
        public string Dis_Name { get; set; }
        public string Dis_Sap_Code { get; set; }
        public string Dis_City { get; set; }
        public string Dis_State { get; set; }
        public string Dis_Name_Warrnty_Card { get; set; }
        public string Dis_Sap_Code_Warrnty_Card { get; set; }
        public string Dis_Address_Warrnty_Card { get; set; }
        public string Dis_City_Warrnty_Card { get; set; }
        public string Dis_State_Warrnty_Card { get; set; }
        public string Dis_Address_ContactNo { get; set; }
        public string Dlr_Name { get; set; }
        public string Dlr_Sap_Code { get; set; }
        public string Dlr_Address { get; set; }
        public string Dlr_City { get; set; }
        public string Dlr_State { get; set; }
        public string Dlr_Phone { get; set; }
        public Nullable<System.DateTime> Product_Purchase_Date { get; set; }
        public string Customer_Name { get; set; }
        public string Customer_Phone { get; set; }
        public string Customer_Address { get; set; }
        public string Customer_State { get; set; }
        public string Customer_City { get; set; }
        public string Customer_email { get; set; }
        public string ModBy { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public string E_Status { get; set; }
        public string Customer_LandLineNo { get; set; }
        public string Form_Number { get; set; }
        public string Scheme_Name { get; set; }
        public string Pin_Code { get; set; }
        public string Remark { get; set; }
        public string Docket_No { get; set; }
        public string Sender_Address { get; set; }
        public string Agency_Remark { get; set; }
        public string Entry_Status { get; set; }
        public string Verification_Status { get; set; }
        public string Verify_status { get; set; }
        public string Verify_Remark { get; set; }
        public string Verify_By { get; set; }
        public Nullable<System.DateTime> Verify_date { get; set; }
        public string Product_Type_V { get; set; }
        public string Customer_Name_V { get; set; }
        public string Customer_Phone_V { get; set; }
        public string Customer_Address_V { get; set; }
        public Nullable<System.DateTime> Product_Purchase_Date_V { get; set; }
    }
}
