//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuminousMpartnerIB.OtpClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OtpClient.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Generating message contract since element name mob from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sendsms", ReplyAction="*")]
        LuminousMpartnerIB.OtpClient.sendsmsResponse sendsms(LuminousMpartnerIB.OtpClient.sendsmsRequest request);
        
        // CODEGEN: Generating message contract since element name mob from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sendsmsIMI", ReplyAction="*")]
        LuminousMpartnerIB.OtpClient.sendsmsIMIResponse sendsmsIMI(LuminousMpartnerIB.OtpClient.sendsmsIMIRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendsmsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendsms", Namespace="http://tempuri.org/", Order=0)]
        public LuminousMpartnerIB.OtpClient.sendsmsRequestBody Body;
        
        public sendsmsRequest() {
        }
        
        public sendsmsRequest(LuminousMpartnerIB.OtpClient.sendsmsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sendsmsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mob;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mess;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string employee;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string token;
        
        public sendsmsRequestBody() {
        }
        
        public sendsmsRequestBody(string mob, string mess, string employee, string token) {
            this.mob = mob;
            this.mess = mess;
            this.employee = employee;
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendsmsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendsmsResponse", Namespace="http://tempuri.org/", Order=0)]
        public LuminousMpartnerIB.OtpClient.sendsmsResponseBody Body;
        
        public sendsmsResponse() {
        }
        
        public sendsmsResponse(LuminousMpartnerIB.OtpClient.sendsmsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sendsmsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sendsmsResult;
        
        public sendsmsResponseBody() {
        }
        
        public sendsmsResponseBody(string sendsmsResult) {
            this.sendsmsResult = sendsmsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendsmsIMIRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendsmsIMI", Namespace="http://tempuri.org/", Order=0)]
        public LuminousMpartnerIB.OtpClient.sendsmsIMIRequestBody Body;
        
        public sendsmsIMIRequest() {
        }
        
        public sendsmsIMIRequest(LuminousMpartnerIB.OtpClient.sendsmsIMIRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sendsmsIMIRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mob;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mess;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string msgtype;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string reftext;
        
        public sendsmsIMIRequestBody() {
        }
        
        public sendsmsIMIRequestBody(string mob, string mess, string token, string msgtype, string reftext) {
            this.mob = mob;
            this.mess = mess;
            this.token = token;
            this.msgtype = msgtype;
            this.reftext = reftext;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendsmsIMIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendsmsIMIResponse", Namespace="http://tempuri.org/", Order=0)]
        public LuminousMpartnerIB.OtpClient.sendsmsIMIResponseBody Body;
        
        public sendsmsIMIResponse() {
        }
        
        public sendsmsIMIResponse(LuminousMpartnerIB.OtpClient.sendsmsIMIResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sendsmsIMIResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sendsmsIMIResult;
        
        public sendsmsIMIResponseBody() {
        }
        
        public sendsmsIMIResponseBody(string sendsmsIMIResult) {
            this.sendsmsIMIResult = sendsmsIMIResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : LuminousMpartnerIB.OtpClient.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<LuminousMpartnerIB.OtpClient.ServiceSoap>, LuminousMpartnerIB.OtpClient.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LuminousMpartnerIB.OtpClient.sendsmsResponse LuminousMpartnerIB.OtpClient.ServiceSoap.sendsms(LuminousMpartnerIB.OtpClient.sendsmsRequest request) {
            return base.Channel.sendsms(request);
        }
        
        public string sendsms(string mob, string mess, string employee, string token) {
            LuminousMpartnerIB.OtpClient.sendsmsRequest inValue = new LuminousMpartnerIB.OtpClient.sendsmsRequest();
            inValue.Body = new LuminousMpartnerIB.OtpClient.sendsmsRequestBody();
            inValue.Body.mob = mob;
            inValue.Body.mess = mess;
            inValue.Body.employee = employee;
            inValue.Body.token = token;
            LuminousMpartnerIB.OtpClient.sendsmsResponse retVal = ((LuminousMpartnerIB.OtpClient.ServiceSoap)(this)).sendsms(inValue);
            return retVal.Body.sendsmsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LuminousMpartnerIB.OtpClient.sendsmsIMIResponse LuminousMpartnerIB.OtpClient.ServiceSoap.sendsmsIMI(LuminousMpartnerIB.OtpClient.sendsmsIMIRequest request) {
            return base.Channel.sendsmsIMI(request);
        }
        
        public string sendsmsIMI(string mob, string mess, string token, string msgtype, string reftext) {
            LuminousMpartnerIB.OtpClient.sendsmsIMIRequest inValue = new LuminousMpartnerIB.OtpClient.sendsmsIMIRequest();
            inValue.Body = new LuminousMpartnerIB.OtpClient.sendsmsIMIRequestBody();
            inValue.Body.mob = mob;
            inValue.Body.mess = mess;
            inValue.Body.token = token;
            inValue.Body.msgtype = msgtype;
            inValue.Body.reftext = reftext;
            LuminousMpartnerIB.OtpClient.sendsmsIMIResponse retVal = ((LuminousMpartnerIB.OtpClient.ServiceSoap)(this)).sendsmsIMI(inValue);
            return retVal.Body.sendsmsIMIResult;
        }
    }
}
